#!/bin/bash

MANIFEST=https://github.com/P-404/platform_manifest
BRANCH=rippa

mkdir -p /tmp/rom
cd /tmp/rom

# Repo init command, that -device,-mips,-darwin,-notdefault part will save you more time and storage to sync, add more according to your rom and choice. Optimization is welcomed! Let's make it quit, and with depth=1 so that no unnecessary things.
repo init --no-repo-verify --depth=1 -u "$MANIFEST" -b "$BRANCH" -g default,-device,-mips,-darwin,-notdefault
git config --global user.name ItsVixano
git config --global user.email vixanonew@gmail.com

# Sync source with -q, no need unnecessary messages, you can remove -q if want! try with -j30 first, if fails, it will try again with -j8
repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j$(nproc --all) || repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j8

# Hax
rm -rf frameworks/native external/fastrpc vendor/qcom/opensource/commonsys-intf/display device/qcom/sepolicy
git clone https://github.com/ItsVixano/android_frameworks_native --depth=1 --single-branch frameworks/native
git clone https://github.com/ItsVixano/platform_hardware_google_pixel --depth=1 --single-branch hardware/google/pixel
git clone https://github.com/P-404/platform_device_404_sepolicy --depth=1 --single-branch device/404/sepolicy
git clone https://github.com/AOSPA/android_external_fastrpc --depth=1 --single-branch external/fastrpc
git clone https://github.com/ItsVixano/android_vendor_qcom_opensource_commonsys-intf_display --depth=1 --single-branch -b rippa-whyred vendor/qcom/opensource/commonsys-intf/display
git clone https://github.com/ItsVixano/android_device_qcom_sepolicy --depth=1 --single-branch device/qcom/sepolicy

# Sync hals
git clone https://github.com/ItsVixano/android_hardware_qcom_display --single-branch -b ruby hardware/qcom/display --depth=1
git clone https://github.com/aospa-whyred/android_hardware_qcom_audio --single-branch -b ruby hardware/qcom/audio --depth=1
git clone https://github.com/aospa-whyred/android_hardware_qcom_media --single-branch -b ruby hardware/qcom/media --depth=1

# Sync dt
rm -rf device/qcom/common vendor/qcom/common
git clone https://github.com/AOSPA/android_device_qcom_common --depth=1 --single-branch device/qcom/common
git clone https://github.com/ThankYouMario/proprietary_vendor_qcom_common --depth=1 --single-branch vendor/qcom/common

git clone https://github.com/ItsVixano/android_device_xiaomi_whyred --single-branch -b rippa device/xiaomi/whyred --depth=1
git clone https://github.com/ItsVixano/android_vendor_xiaomi_whyred --single-branch -b rippa vendor/xiaomi/whyred --depth=1
git clone https://github.com/SreekanthPalakurthi/kranul --single-branch -b eas kernel/xiaomi/whyred --depth=1
