#!/bin/bash

MANIFEST=git://github.com/crdroidandroid/android.git
BRANCH=11.0

mkdir -p /tmp/rom
cd /tmp/rom

# Repo init command, that -device,-mips,-darwin,-notdefault part will save you more time and storage to sync, add more according to your rom and choice. Optimization is welcomed! Let's make it quit, and with depth=1 so that no unnecessary things.
repo init --no-repo-verify --depth=1 -u "$MANIFEST" -b "$BRANCH" -g default,-device,-mips,-darwin,-notdefault
git config --global user.name Erickeagle3
git config --global user.email sayanchakraborty334@gmail.com

# Sync source with -q, no need unnecessary messages, you can remove -q if want! try with -j30 first, if fails, it will try again with -j8
repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j$(nproc --all) || repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j8

# Sync stuffs
find hardware/qcom-caf/msm8996/display hardware/qcom-caf/msm8996/audio hardware/qcom-caf/msm8996/media .repo/ -delete
git clone https://github.com/Erickeagle3/new-r-dt.git -b cr7 device/xiaomi/mido --depth=1
git clone https://github.com/Erickeagle3/proprietary_vendor_xiaomi.git -b cr7 vendor/xiaomi/mido --depth=1
git clone https://github.com/zeelog/android_kernel_xiaomi_mido.git -b lineage-18.1 kernel/xiaomi/mido --depth=1
git clone https://github.com/android-eleven/hardware_qcom_display -b caf-msm8996-r hardware/qcom-caf/msm8996/display --depth=1
git clone https://github.com/android-eleven/hardware_qcom_audio -b caf-msm8996-r hardware/qcom-caf/msm8996/audio --depth=1
git clone https://github.com/android-eleven/hardware_qcom_media -b caf-msm8996-r hardware/qcom-caf/msm8996/media --depth=1
